### PR TITLE
Use full variable syntax for with_items

### LINKED ISSUE #50: [DEPRECATION WARNING]: Using bare variables is deprecated
TASK [flyapen.jenkins : Install dependencies] **********************************
[DEPRECATION WARNING]: Using bare variables is deprecated. Update your 
playbooks so that the environment value uses the full variable syntax 
('{{jenkins.deb.dependencies}}').
This feature will be removed in a future 
release. Deprecation warnings can be disabled by setting 
deprecation_warnings=False in ansible.cfg.

### PR DESCRIPTION
**Pull request by takluyver**
Closes #50

This is required as of Ansible 2.2 - the 'bare variables' no longer work.

### CODE REVIEW

**Comment by takluyver** [comment]
From the [Ansible 2 porting guide](https://docs.ansible.com/ansible/porting_guide_2.0.html#deprecated):

> Bare variables in with_ loops should instead use the “{{var}}” syntax, which helps eliminate ambiguity.

Also, [this SO answer](http://stackoverflow.com/a/36901265/434217) refers to this change.

**Comment by ZeusF1** [comment]
yeah did same https://github.com/ICTO/ansible-jenkins/pull/57

**Comment by takluyver** [comment]
Ping @flyapen - this is a simple change which I hope should be low-risk.

**Comment by kristofkeppens** [comment]
Thanks for the pull request!

**Comment by takluyver** [comment]
Thanks for merging it :-)

**Pull request merged**
